
// const mongoose = require('mongoose');

// const Materialschema = new mongoose.Schema({
//     course: String,
//     semester: String,
//     subject: { type: String, required: true },
//     description: String,

//     // --- Critical Fixes Below ---

//     // The unique filename generated by Multer (e.g., '17000000-filename.pdf')
//     storedFilename: { type: String, required: true },
    
//     // The original, user-friendly name (e.g., 'Chapter 1 Notes.pdf')
//     originalName: { type: String, required: true },
    
//     // The file's MIME type (e.g., 'application/pdf')
//     mimetype: { type: String, required: true },

//     // File size in bytes
//     size: { type: Number, required: true },

//     // Optional: A relative URL for simple access (if you use express.static)
//     fileUrl: { type: String, required: true }, 
    
//     uploadedBy: { 
//         type: mongoose.Schema.Types.ObjectId, 
//         ref: 'User',
//         required: true
//     }
// }, { timestamps: true });

// Materialschema.index({ 
//     subject: 'text', 
//     description: 'text',
//     originalName: 'text' 
// });

// module.exports = mongoose.model('Material', Materialschema);
const mongoose = require('mongoose');

const MaterialSchema = new mongoose.Schema({
    course: String,
    semester: String,
    subject: { type: String, required: true },
    description: String,

    // --- Cloudinary Integration Fields ---

    // Cloudinary 'public_id' (e.g., 'course-materials/17000-filename')
    // REQUIRED: We need this to generate Signed URLs and to Delete files.
    storedFilename: { type: String, required: true },
    
    // The user's original filename (e.g., 'Chapter 1 Notes.pdf')
    originalName: { type: String, required: true },
    
    // MIME type (e.g., 'application/pdf') - Used to toggle resource_type (image vs raw)
    mimetype: { type: String, required: true },

    // File size in bytes
    size: { type: Number, required: true },

    // Cloudinary Secure URL. 
    // NOTE: Since we use type: 'authenticated', this URL will NOT work publicly 
    // without a signature, but it is good to keep for reference.
    fileUrl: { type: String, required: true }, 
    
    uploadedBy: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User',
        required: true
    }
}, { timestamps: true });

// Text indexes for search functionality
MaterialSchema.index({ 
    subject: 'text', 
    description: 'text',
    originalName: 'text' 
});

module.exports = mongoose.model('Material', MaterialSchema);